name: Build, Test, and Release

on:
  push:
    branches: [ master, main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.10'

      - name: Build
        run: |
          make build

      - name: Test
        run: |
          make test

      - name: Validate
        run: |
          make validate

      - name: Upload binary artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docker-machine
          path: bin/docker-machine

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.10'

      - name: Build release binaries
        run: |
          export USE_CONTAINER=true
          make build

      - name: Generate checksums
        run: |
          cd bin
          sha256sum docker-machine* > SHA256SUMS

      - name: Get release version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Generate release notes
        run: |
          VERSION=${{ steps.get_version.outputs.VERSION }}
          CHANGELOG=$(awk "/# ${VERSION//v/}/,/# [0-9]+/" CHANGELOG.md | sed '1d;$d')
          CONTRIBUTORS=$(git log --format='%aN' $(git describe --tags --abbrev=0 HEAD^)..HEAD | sort -u | awk '{print "- " $0}')
          CHECKSUM=$(cat bin/SHA256SUMS)
          
          cat script/release/github-release-template.md | \
            sed "s/{{VERSION}}/$VERSION/g" | \
            sed "s/{{CHANGELOG}}/$CHANGELOG/g" | \
            sed "s/{{CONTRIBUTORS}}/$CONTRIBUTORS/g" | \
            sed "s/{{CHECKSUM}}/$CHECKSUM/g" > RELEASE_NOTES.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/docker-machine*
            bin/SHA256SUMS
          body_path: RELEASE_NOTES.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
