name: Docker Machine Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    env:
      S3_BASE_URL: https://gitlab-docker-machine-downloads.s3.amazonaws.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set release version
        id: set_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.VERSION }}
          draft: false
          prerelease: ${{ contains(env.VERSION, '-rc') }}
          body: |
            New release of Docker Machine is out!
            
            ## Download Links
            
            ### Binaries
            - [macOS amd64](${{ env.S3_BASE_URL }}/${{ env.VERSION }}/docker-machine-Darwin-x86_64)
            - [Linux amd64](${{ env.S3_BASE_URL }}/${{ env.VERSION }}/docker-machine-Linux-x86_64)
            - [Linux arm](${{ env.S3_BASE_URL }}/${{ env.VERSION }}/docker-machine-Linux-armhf)
            - [Linux arm64](${{ env.S3_BASE_URL }}/${{ env.VERSION }}/docker-machine-Linux-aarch64)
            - [OpenBSD amd64](${{ env.S3_BASE_URL }}/${{ env.VERSION }}/docker-machine-OpenBSD-x86_64)
            - [Windows amd64](${{ env.S3_BASE_URL }}/${{ env.VERSION }}/docker-machine-Windows-x86_64.exe)
            
            ### Verification
            - [Checksums](${{ env.S3_BASE_URL }}/${{ env.VERSION }}/release.sha256)
            - [Checksums GPG signature](${{ env.S3_BASE_URL }}/${{ env.VERSION }}/release.sha256.asc)
            - [Other release artifacts](${{ env.S3_BASE_URL }}/${{ env.VERSION }}/index.html)
          files: |
            # If you have local files to upload, list them here
            # Otherwise, the S3 links will be included in the release body

  publish-dockerhub:
    name: Publish to DockerHub
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            khulnasoft/docker-machine:latest
            khulnasoft/docker-machine:${{ env.VERSION }}